# We'll generate each platform page from this template
platforms = [
    {
        "file": "portal-schwab.html",
        "name": "Charles Schwab",
        "category": "Custodian",
        "tagline": "Your accounts, always in view.",
        "description": "Charles Schwab is one of the nation's largest and most trusted custodians. As your account custodian, Schwab holds your assets independently from Pine Valley Investments — giving you direct visibility and control of your money at all times.",
        "login_url": "https://client.schwab.com",
        "login_label": "Login to Schwab",
        "color": "#00A0B0",
        "logo_color": "#00A0B0",
        "features": [
            {"icon": "📊", "title": "Account Balances & Holdings", "desc": "View your complete portfolio in real time — positions, values, and allocation breakdowns across all account types."},
            {"icon": "📄", "title": "Statements & Tax Documents", "desc": "Access monthly statements, trade confirmations, 1099s, and all tax-related documents in one place."},
            {"icon": "🔄", "title": "Transaction History", "desc": "Review a complete history of every trade, transfer, and activity across your accounts."},
            {"icon": "🔒", "title": "SIPC Protected", "desc": "Your assets held at Schwab are protected by SIPC up to $500,000, with additional coverage through Lloyd's of London."},
            {"icon": "📱", "title": "Mobile App Access", "desc": "Full account access on iOS and Android — check balances, view statements, and monitor your portfolio on the go."},
            {"icon": "🏦", "title": "Independent Custody", "desc": "Schwab holds your assets completely independently from PVI, providing an important additional layer of oversight and security."},
        ],
        "why": "As a fiduciary RIA, Pine Valley Investments never holds client assets directly. Schwab serves as your independent custodian — meaning your money is always held in your name, separately from our firm.",
    },
    {
        "file": "portal-altruist.html",
        "name": "Altruist",
        "category": "Custodian",
        "tagline": "Modern custody. Built for the independent advisor.",
        "description": "Altruist is a modern, technology-forward custodian built specifically for independent RIAs. Designed from the ground up with transparency and efficiency in mind, Altruist gives you a clean, intuitive view of your assets.",
        "login_url": "https://client.altruist.com",
        "login_label": "Login to Altruist",
        "color": "#5B5BD6",
        "logo_color": "#5B5BD6",
        "features": [
            {"icon": "⚡", "title": "Real-Time Account View", "desc": "See your portfolio values, holdings, and performance updated in real time with a clean, modern interface."},
            {"icon": "📄", "title": "Statements & Documents", "desc": "Access your account statements, trade confirmations, and tax documents quickly and easily."},
            {"icon": "💰", "title": "Commission-Free Trading", "desc": "Altruist offers commission-free trading, which means lower costs that stay in your portfolio."},
            {"icon": "🔒", "title": "SIPC Protected", "desc": "Assets held at Altruist are protected by SIPC up to $500,000, with additional excess coverage."},
            {"icon": "📱", "title": "Digital-First Experience", "desc": "Purpose-built for the modern investor — a clean, intuitive interface available on all devices."},
            {"icon": "🏦", "title": "Independent Custody", "desc": "Like Schwab, Altruist holds your assets independently from PVI — your money is always in your name."},
        ],
        "why": "Altruist represents the next generation of independent custody — built with technology-first principles that reduce costs and improve the client experience without sacrificing security.",
    },
    {
        "file": "portal-emoney.html",
        "name": "eMoney",
        "category": "Financial Planning",
        "tagline": "Your complete financial life, in one view.",
        "description": "eMoney is PVI's primary financial planning platform. It aggregates every dimension of your financial life — investments, insurance, real estate, liabilities, and more — into a single, holistic dashboard. Complimentary for all PVI clients.",
        "login_url": "https://wealth.emaplan.com/ema/SignIn?ema/ria/pinevalley",
        "login_label": "Login to eMoney",
        "color": "#0077C8",
        "logo_color": "#0077C8",
        "features": [
            {"icon": "🌐", "title": "Complete Net Worth View", "desc": "See everything — investment accounts, real estate, insurance, liabilities, and more — aggregated into a single net worth snapshot."},
            {"icon": "📈", "title": "Cash Flow Analysis", "desc": "Understand your income, spending, and savings patterns with detailed cash flow tracking and projections."},
            {"icon": "🎯", "title": "Goal Tracking", "desc": "Set and track progress toward retirement, education, major purchases, or any custom financial goal."},
            {"icon": "🔮", "title": "Scenario Modeling", "desc": "Run 'what-if' scenarios — what happens if you retire early? Sell your business? Receive an inheritance? See the impact instantly."},
            {"icon": "📊", "title": "Investment Performance", "desc": "Monitor portfolio performance, risk exposure, and allocation across all your accounts in one unified view."},
            {"icon": "🆓", "title": "Complimentary for All PVI Clients", "desc": "eMoney access is included at no additional cost as part of your relationship with Pine Valley Investments."},
        ],
        "why": "eMoney is the platform your PVI advisor uses to build and monitor your financial plan. Having access to the same view your advisor sees means better, more informed conversations — and greater confidence in your plan.",
    },
    {
        "file": "portal-rightcapital.html",
        "name": "RightCapital",
        "category": "Financial Planning",
        "tagline": "Retirement clarity. Tax efficiency. Estate confidence.",
        "description": "RightCapital is a sophisticated financial planning platform focused on retirement income, tax optimization, and estate planning. Work collaboratively with your PVI advisor through a shared, interactive planning environment.",
        "login_url": "https://app.rightcapital.com",
        "login_label": "Login to RightCapital",
        "color": "#2DB5A3",
        "logo_color": "#2DB5A3",
        "features": [
            {"icon": "🏖️", "title": "Retirement Income Planning", "desc": "Model your retirement income streams — Social Security, pensions, withdrawals, and more — to find the optimal distribution strategy."},
            {"icon": "💸", "title": "Tax Planning & Optimization", "desc": "Visualize your tax situation year by year and identify strategies like Roth conversions, tax-loss harvesting, and bracket management."},
            {"icon": "🏛️", "title": "Estate Planning", "desc": "Map out your estate — beneficiaries, trusts, and asset transfer strategies — to ensure your legacy is protected."},
            {"icon": "📋", "title": "Social Security Optimization", "desc": "Model different Social Security claiming strategies to maximize your lifetime benefit."},
            {"icon": "🤝", "title": "Collaborative Planning", "desc": "Your RightCapital plan is built and maintained collaboratively with your PVI advisor — you both see the same picture."},
            {"icon": "📱", "title": "Interactive Dashboards", "desc": "Explore your plan through intuitive charts and dashboards that make complex planning concepts easy to understand."},
        ],
        "why": "RightCapital is where the detailed, long-term planning happens. It's particularly powerful for pre-retirees and retirees navigating complex decisions around income, taxes, and legacy planning.",
    },
    {
        "file": "portal-tamarac.html",
        "name": "WealthView · Tamarac",
        "category": "Data Aggregation & Reporting",
        "tagline": "Institutional-grade portfolio reporting, built for you.",
        "description": "Tamarac's WealthView is PVI's dedicated client reporting portal. It gives you institutional-quality performance reporting, tax reporting, and portfolio analytics — the same level of data sophistication used by large institutional investors.",
        "login_url": "https://pinevalley.portal.tamaracinc.com",
        "login_label": "Login to WealthView",
        "color": "#003865",
        "logo_color": "#003865",
        "features": [
            {"icon": "📈", "title": "Performance Reporting", "desc": "See time-weighted and money-weighted returns across any time period — with benchmarks for full context."},
            {"icon": "📊", "title": "Portfolio Analytics", "desc": "Drill into allocation, sector exposure, risk metrics, and attribution — understand exactly what's driving your returns."},
            {"icon": "🗂️", "title": "Tax & Cost Basis Reporting", "desc": "Access detailed cost basis, realized/unrealized gain/loss reports, and tax lot information for every holding."},
            {"icon": "📄", "title": "Statements & Documents", "desc": "Download quarterly performance statements, account statements, and custom reports on demand."},
            {"icon": "🔗", "title": "Consolidated View", "desc": "View all of your PVI-managed accounts in a single consolidated report — regardless of which custodian holds them."},
            {"icon": "🏆", "title": "Institutional Quality", "desc": "The same reporting infrastructure used by endowments and institutional investors, now available for your personal portfolio."},
        ],
        "why": "Tamarac's WealthView is how PVI delivers institutional-quality transparency to every client. It goes far beyond basic account statements — giving you the analytical depth to truly understand how your portfolio is performing.",
    },
    {
        "file": "portal-monarch.html",
        "name": "Monarch Money",
        "category": "Data Aggregation & Reporting",
        "tagline": "Every account. Every dollar. One clear picture.",
        "description": "Monarch Money is a personal finance platform that connects all your financial accounts — bank accounts, credit cards, loans, investments, and more — into a single, beautifully organized dashboard. Track your net worth and spending with clarity.",
        "login_url": "https://app.monarchmoney.com",
        "login_label": "Login to Monarch",
        "color": "#4F46E5",
        "logo_color": "#4F46E5",
        "features": [
            {"icon": "🔗", "title": "Connect All Your Accounts", "desc": "Link bank accounts, credit cards, mortgages, investment accounts, and more — automatically synced and organized."},
            {"icon": "💰", "title": "Net Worth Tracking", "desc": "See your complete net worth — assets minus liabilities — updated automatically as accounts sync."},
            {"icon": "📊", "title": "Spending & Budgeting", "desc": "Understand your spending patterns by category, set budgets, and track progress toward your financial goals."},
            {"icon": "📈", "title": "Investment Tracking", "desc": "Monitor all your investment accounts — including those not managed by PVI — in one consolidated view."},
            {"icon": "🎯", "title": "Goal Setting", "desc": "Set savings goals and track progress in real time — emergency fund, vacation, home purchase, or anything else."},
            {"icon": "🔔", "title": "Alerts & Insights", "desc": "Get notified of unusual spending, large transactions, and personalized insights to help you stay on track."},
        ],
        "why": "Monarch gives you a complete picture of your financial life — not just what PVI manages, but everything. This broader view helps your advisor give more comprehensive guidance and helps you stay in control between meetings.",
    },
]

print(f"Defined {len(platforms)} platforms")
for p in platforms:
    print(f"  - {p['name']} ({p['category']})")
